postgresql_version: 14
postgresql_data_dir: /data/patroni
postgresql_bin_path: /usr/pgsql-14/bin
postgresql_config_path: /data/patroni
postgresql_daemon: postgresql-14.service
postgresql_packages:
  - postgresql14
  - postgresql14-server
  - postgresql14-libs
  - postgresql14-contrib
  - postgresql14-devel

postgresql_hba_entries:
  - { type: host, database: all, user: '{{ postgres_sql_username }}', address: all, auth_method: md5 }
  - { type: local, database: all, user: postgres, auth_method: peer }
  - { type: local, database: all, user: all, auth_method: peer }
  - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5 }
  - { type: host, database: all, user: all, address: '::1/128', auth_method: md5 }

postgresql_users:
  - name: '{{ postgres_sql_username }}'
    password: '{{ postgres_sql_password }}'
    encrypted: true

postgresql_databases:
  - name: '{{ postgresql_database_name }}'

postgresql_global_config_options:
  - option: listen_addresses
    value: '*'
  - option: unix_socket_directories
    value: '{{ postgresql_unix_socket_directories | join(",") }}'
  - option: data_directory
    value: "/data/patroni"