---
all:
  children:
    postgresql:
      hosts:
        pg-14-builder:
        pg-14-test:
    builders:
      hosts:
        pg-14-builder:
    pg14:
      hosts:
        pg-14-builder:
        pg-14-test:
    test:
      hosts:
        pg-14-test:

