---
- hosts: all
  roles:
  - role: common

- hosts: postgresql
  become: true
  roles:
    - role: postgresql_preconfig
    - role: geerlingguy.postgresql
    - role: postgresql_postconfig

- hosts: builders
  roles:
  - role: extension_builder

- hosts: test
  roles:
  - role: test